name = "maniac-garage"
compatibility_date = "2026-05-28"
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "maniac-garage"
database_id = "<D1_DATABASE_ID>"

[[r2_buckets]]
binding = "ASSETS"
bucket_name = "maniac-garage-assets"
