name = "maniac-garage"
compatibility_date = "2026-05-28"
pages_build_output_dir = "out"

[[d1_databases]]
binding = "DB"
database_name = "maniac-garage-dev"
database_id = "3eb4039d-f12f-4d9b-be5a-047b2a714012"

# R2 binding will be added after the upload flow is implemented.
